---
pid: /var/run/game_server.pid
timeout: 30
wait: 30
log: log/thin/game_server.log
max_conns: 1024
require: []

environment: production
max_persistent_conns: 512
servers: 2
daemonize: true
chdir: /var/www/game_server/current
socket: /var/run/game_server.sock